package com.dzb.partyBranch.model.po;
// Generated 2019-8-2 21:03:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseMenu generated by hbm2java
 */
@Entity
@Table(name = "base_menu", catalog = "lt_dzb")
public class BaseMenu implements java.io.Serializable {

	private Integer id;
	private String name;
	private int sort;
	private int pid;
	private Integer status;
	private String url;
	private String icon;

	public BaseMenu() {
	}

	public BaseMenu(String name, int sort, int pid, String url) {
		this.name = name;
		this.sort = sort;
		this.pid = pid;
		this.url = url;
	}

	public BaseMenu(String name, int sort, int pid, Integer status, String url, String icon) {
		this.name = name;
		this.sort = sort;
		this.pid = pid;
		this.status = status;
		this.url = url;
		this.icon = icon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sort", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	@Column(name = "pid", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "url", nullable = false, length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "icon", length = 100)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

}
