package com.dzb.partyBranch.model.po;
// Generated 2018-11-9 14:56:09 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "part_area")
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String areaName;
	private Integer cityId;
	private boolean primaryall;

	public Area() {
		
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "area_name")
	public String getAreaName() {
		return areaName;
	}


	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "city_id")
	public Integer getCityId() {
		return cityId;
	}


	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "primaryall")
	public boolean getPrimaryall() {
		return primaryall;
	}

	
	public void setPrimaryall(boolean primaryall) {
		this.primaryall = primaryall;
	}

	

}