package com.dzb.partyBranch.model.po;
// Generated 2018-11-9 14:56:09 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "part_enterprise")
public class EnterPrise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer departmentNum;
	private Integer typeId;
	private Integer position;
	private Integer areaId;
	private boolean authentication;

	public EnterPrise() {
		
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "department_num")
	public Integer getDepartmentNum() {
		return departmentNum;
	}


	public void setDepartmentNum(Integer departmentNum) {
		this.departmentNum = departmentNum;
	}

	@Column(name = "type_id")
	public Integer getTypeId() {
		return typeId;
	}


	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return position;
	}


	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "area_id")
	public Integer getAreaId() {
		return areaId;
	}


	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}


	public boolean isAuthentication() {
		return authentication;
	}


	public void setAuthentication(boolean authentication) {
		this.authentication = authentication;
	}

	

}