package com.dzb.partyBranch.model.po;
// Generated 2018-11-9 14:56:09 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "part_branch")
public class PartyBranch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String partName;
	private Integer enterpriseId;
	private Integer pelCount;

	public PartyBranch() {
		
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "part_name")
	public String getPartName() {
		return partName;
	}

	
	public void setPartName(String partName) {
		this.partName = partName;
	}

	@Column(name = "enterprise_id")
	public Integer getEnterpriseId() {
		return enterpriseId;
	}


	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@Column(name = "pel_count")
	public Integer getPelCount() {
		return pelCount;
	}


	public void setPelCount(Integer pelCount) {
		this.pelCount = pelCount;
	}

	

}